import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

import Sidebar from "@/components/sidebar";
import Header from "@/components/header";
import { getAllEmails } from "@/lib/fetch";
import { EmailData } from "@/lib/interface";
import { cookies } from "next/headers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dataEmail: EmailData[] = await getAllEmails();
  const token = await (await cookies()).get("token")?.value;

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${plusJakartaSans.variable} antialiased bg-[#F6F9FF]`}
      >
        <div className="flex">
          <Sidebar data={dataEmail} token={`${token}`} />
          <div className="flex-1">
            <Header />
            {children}
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
